application:
  name: Spring DDD Starter
  version: 0.0.1-SNAPSHOT
security:
  frontend-success: /api
  users:
  # define users through env variables, giving name, password, roles
spring:
  application:
    name: Spring DDD Starter
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      naming:
        implicit-strategy: com.example.app._infrastructure.persistence.EmbeddedPrefixImplicitNamingStrategy
  modulith:
    events:
      republish-outstanding-events-on-restart: true
springdoc:
  swagger-ui:
    csrf:
      enabled: true
      use-local-storage: true
management:
  endpoints:
    web:
      exposure:
        include: [health,actuator,info]
---
spring:
  profiles:
    active: dev
security:
  frontend-success: /api
  users:
    - name: user
      password: 1234
      roles: USER
    - name: admin
      password: 1234
      roles: [USER, ADMIN]
